spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

openai:
  secret-key: ${CHATGPT_SECRET_KEY}
  url:
    model: "https://api.openai.com/v1/models"
    model-list: "https://api.openai.com/v1/models/"
    legacy-prompt: "https://api.openai.com/v1/completions"
    prompt: "https://api.openai.com/v1/chat/completions"
